{
*******************************************************
  This is generated by "Source Generator" at 01/07/19 10:54:40        

Parameters: 
ListClassName=Ts0ControlList
ListUnitName=s0ControlList
TargetClassName=TControl
TargetUnitName=Controls

    "Source Generator" Copyright(c) 2001 Takeshi Akima 
*******************************************************

$History: s0ControlList.pas $
 * 
 * *****************  Version 4  *****************
 * User: Akima        Date: 02/03/09   Time: 17:40
 * Updated in $/D5/source/VCL
 * 
 * *****************  Version 3  *****************
 * User: Akima        Date: 02/03/04   Time: 21:53
 * Updated in $/source/D6VCLIntegrated
 * CLX対応してます・・・・
 * 
 * *****************  Version 2  *****************
 * User: Akima        Date: 02/02/28   Time: 23:25
 * Updated in $/source/D5Integrated
 * 接頭辞を変更。xxSX～にした。
 * 
 * *****************  Version 1  *****************
 * User: Akima        Date: 01/07/30   Time: 10:07
 * Created in $/source/p0control
 * 新規作成

}
unit s0ControlList;

interface

uses
  SysUtils, Classes, Contnrs,
  Controls;

type
  Ts0ControlList = class(TComponentList)
  private
  protected
    function GetItems(Index: Integer): TControl;
    procedure SetItems(Index: Integer; AItem: TControl);
  public
    function Add(AItem: TControl): Integer;
    function Remove(AItem: TControl): Integer;
    function IndexOf(AItem: TControl): Integer;
    procedure Insert(Index: Integer; AItem: TControl);
    property Items[Index: Integer]: TControl read GetItems write SetItems; default;
    function First: TControl;
    function Last: TControl;
  end;

implementation

{ Ts0ControlList }

function Ts0ControlList.Add(AItem: TControl): Integer;
begin
  Result := inherited Add(AItem);
end;

function Ts0ControlList.First: TControl;
begin
  Result := TControl( inherited First );
end;

function Ts0ControlList.GetItems(Index: Integer): TControl;
begin
  Result := TControl( inherited Items[Index] );
end;

function Ts0ControlList.IndexOf(AItem: TControl): Integer;
begin
  Result := inherited IndexOf(AItem);
end;

procedure Ts0ControlList.Insert(Index: Integer;
  AItem: TControl);
begin
  inherited Insert(Index, AItem);
end;

function Ts0ControlList.Last: TControl;
begin
  Result := TControl( inherited Last );
end;

function Ts0ControlList.Remove(AItem: TControl): Integer;
begin
  Result := inherited Remove(AItem);
end;

procedure Ts0ControlList.SetItems(Index: Integer; AItem: TControl);
begin
  inherited Items[Index] := AItem;
end;

end.
